server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: job-seeker

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
